using AbpCustomizeLeptonXLite.EntityFrameworkCore;
using Xunit;

namespace AbpCustomizeLeptonXLite.EntityFrameworkCore;

public class AbpCustomizeLeptonXLiteEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<AbpCustomizeLeptonXLiteEntityFrameworkCoreFixture>
{

}
