using Volo.Abp;

namespace AbpCustomizeLeptonXLite.EntityFrameworkCore;

public abstract class AbpCustomizeLeptonXLiteEntityFrameworkCoreTestBase : AbpCustomizeLeptonXLiteTestBase<AbpCustomizeLeptonXLiteEntityFrameworkCoreTestModule>
{

}
